spring:
  application:
    name: alora-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/alora
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public

app:
  frontend-url: "http://192.168.1.196:5173/?token="
  gemini-api-key: ${GEMINI_API_KEY}
  jwt-secret: ${JWT_SECRET}

server:
  port: 8080
  address: 0.0.0.0